hugover = "0.69.0"

[[serve]]
  key = "default"
  config = "config.toml"

[[build]]
  key = "default"
  config = "config.toml"


[[singles]]
  key = "mainConfig"
  title = "Algemein"
  file = "config.toml"
  dataformat = "toml"


  [[singles.fields]]
    key = "title"
    title = "Titel der Seite"
    type = "string"
    tip = "Your page title."

  [[singles.fields]]
    key = "baseURL"
    title = "Url der Seite"
    type = "string"
    tip = "Your site URL."

  [[singles.fields]]
    key = "theme"
    title = "Theme"
    type = "readonly"
    tip = "The current theme."

  [[singles.fields]]
    key = "defaultContentLanguage"
    title = "Sprache"
    type = "select"
    [[singles.fields.options]]
      value = "de"
      text = "Deutsch"

    [[singles.fields.options]]
      value = "en"
      text = "Englisch"

  [[singles.fields]]
    key = "googleAnalytics"
    title = "Google Analytics"
    type = "string"
    tip = "Provide a Google Analitics Tracking Code to enable analytics."

  [[singles.fields]]
    key = "enableRobotsTXT"
    title = "Enable Robots"
    type = "boolean"
    default = true
    tip = "If you want your page to be indexed, keep this enabled."
